import unittest
import holmes_extractor as holmes
from threading import Thread
from queue import Queue

manager = holmes.Manager('en_core_web_lg')
manager.parse_and_register_document(
        "The hungry lion chased the angry gnu.", 'lion')
manager.parse_and_register_document(
        "The hungry tiger chased the angry gnu.", 'tiger')
manager.parse_and_register_document(
        "The hungry panther chased the angry gnu.", 'panther')
manager.parse_and_register_document(
        "I saw a donkey. It was chasing the angry gnu.", 'donkey')
manager.register_search_phrase('A gnu is chased')
manager.register_search_phrase('An angry gnu')
manager.register_search_phrase('A tiger chases')

NUMBER_OF_THREADS = 20

class MultithreadingTest(unittest.TestCase):

    def _match_against_documents_within_thread(self, queue, search_phrase):
        queue.put(manager.match_documents_against(search_phrase))

    def _inner_match_against_documents(self, search_phrase, expected_output):
        queue = Queue()
        for i in range(NUMBER_OF_THREADS):
            t = Thread(target=self._match_against_documents_within_thread,
                    args=(queue, search_phrase))
            t.start()
        for i in range(NUMBER_OF_THREADS):
            self.assertEqual(queue.get(True, 5), expected_output)

    def _match_against_search_phrases_within_thread(self, queue, document):
        queue.put(manager.match_search_phrases_against(document))

    def _inner_match_against_search_phrases(self, document, expected_output):
        queue = Queue()
        for i in range(NUMBER_OF_THREADS):
            t = Thread(target=self._match_against_search_phrases_within_thread,
                    args=(queue, document))
            t.start()
        for i in range(NUMBER_OF_THREADS):
            self.assertEqual(queue.get(True, 5), expected_output)

    def test_multithreading_matching_against_documents(self):
        self._inner_match_against_documents("A gnu is chased",
        [{'search_phrase': 'A gnu is chased', 'document': 'lion', 'index_within_document': 3, 'sentences_within_document': 'The hungry lion chased the angry gnu.', 'negated': False, 'uncertain': False, 'involves_coreference': False, 'overall_similarity_measure': '1.0', 'word_matches': [{'search_phrase_word': 'gnu', 'document_word': 'gnu', 'document_phrase': 'the angry gnu', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'gnu'}, {'search_phrase_word': 'chase', 'document_word': 'chase', 'document_phrase': 'chased', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'chase'}]}, {'search_phrase': 'A gnu is chased', 'document': 'tiger', 'index_within_document': 3, 'sentences_within_document': 'The hungry tiger chased the angry gnu.', 'negated': False, 'uncertain': False, 'involves_coreference': False, 'overall_similarity_measure': '1.0', 'word_matches': [{'search_phrase_word': 'gnu', 'document_word': 'gnu', 'document_phrase': 'the angry gnu', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'gnu'}, {'search_phrase_word': 'chase', 'document_word': 'chase', 'document_phrase': 'chased', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'chase'}]}, {'search_phrase': 'A gnu is chased', 'document': 'panther', 'index_within_document': 3, 'sentences_within_document': 'The hungry panther chased the angry gnu.', 'negated': False, 'uncertain': False, 'involves_coreference': False, 'overall_similarity_measure': '1.0', 'word_matches': [{'search_phrase_word': 'gnu', 'document_word': 'gnu', 'document_phrase': 'the angry gnu', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'gnu'}, {'search_phrase_word': 'chase', 'document_word': 'chase', 'document_phrase': 'chased', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'chase'}]}, {'search_phrase': 'A gnu is chased', 'document': 'donkey', 'index_within_document': 7, 'sentences_within_document': 'It was chasing the angry gnu.', 'negated': False, 'uncertain': False, 'involves_coreference': False, 'overall_similarity_measure': '1.0', 'word_matches': [{'search_phrase_word': 'gnu', 'document_word': 'gnu', 'document_phrase': 'the angry gnu', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'gnu'}, {'search_phrase_word': 'chase', 'document_word': 'chase', 'document_phrase': 'chasing', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'chase'}]}])
        self._inner_match_against_documents("An angry gnu",
        [{'search_phrase': 'An angry gnu', 'document': 'lion', 'index_within_document': 6, 'sentences_within_document': 'The hungry lion chased the angry gnu.', 'negated': False, 'uncertain': False, 'involves_coreference': False, 'overall_similarity_measure': '1.0', 'word_matches': [{'search_phrase_word': 'angry', 'document_word': 'angry', 'document_phrase': 'angry', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'angry'}, {'search_phrase_word': 'gnu', 'document_word': 'gnu', 'document_phrase': 'the angry gnu', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'gnu'}]}, {'search_phrase': 'An angry gnu', 'document': 'tiger', 'index_within_document': 6, 'sentences_within_document': 'The hungry tiger chased the angry gnu.', 'negated': False, 'uncertain': False, 'involves_coreference': False, 'overall_similarity_measure': '1.0', 'word_matches': [{'search_phrase_word': 'angry', 'document_word': 'angry', 'document_phrase': 'angry', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'angry'}, {'search_phrase_word': 'gnu', 'document_word': 'gnu', 'document_phrase': 'the angry gnu', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'gnu'}]}, {'search_phrase': 'An angry gnu', 'document': 'panther', 'index_within_document': 6, 'sentences_within_document': 'The hungry panther chased the angry gnu.', 'negated': False, 'uncertain': False, 'involves_coreference': False, 'overall_similarity_measure': '1.0', 'word_matches': [{'search_phrase_word': 'angry', 'document_word': 'angry', 'document_phrase': 'angry', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'angry'}, {'search_phrase_word': 'gnu', 'document_word': 'gnu', 'document_phrase': 'the angry gnu', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'gnu'}]}, {'search_phrase': 'An angry gnu', 'document': 'donkey', 'index_within_document': 10, 'sentences_within_document': 'It was chasing the angry gnu.', 'negated': False, 'uncertain': False, 'involves_coreference': False, 'overall_similarity_measure': '1.0', 'word_matches': [{'search_phrase_word': 'angry', 'document_word': 'angry', 'document_phrase': 'angry', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'angry'}, {'search_phrase_word': 'gnu', 'document_word': 'gnu', 'document_phrase': 'the angry gnu', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'gnu'}]}])
        self._inner_match_against_documents("A tiger chases a gnu",
        [{'search_phrase': 'A tiger chases a gnu', 'document': 'tiger', 'index_within_document': 3, 'sentences_within_document': 'The hungry tiger chased the angry gnu.', 'negated': False, 'uncertain': False, 'involves_coreference': False, 'overall_similarity_measure': '1.0', 'word_matches': [{'search_phrase_word': 'tiger', 'document_word': 'tiger', 'document_phrase': 'The hungry tiger', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'tiger'}, {'search_phrase_word': 'chase', 'document_word': 'chase', 'document_phrase': 'chased', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'chase'}, {'search_phrase_word': 'gnu', 'document_word': 'gnu', 'document_phrase': 'the angry gnu', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'gnu'}]}])
        self._inner_match_against_documents("A donkey chases",
        [{'search_phrase': 'A donkey chases', 'document': 'donkey', 'index_within_document': 7, 'sentences_within_document': 'I saw a donkey. It was chasing the angry gnu.', 'negated': False, 'uncertain': False, 'involves_coreference': True, 'overall_similarity_measure': '1.0', 'word_matches': [{'search_phrase_word': 'donkey', 'document_word': 'donkey', 'document_phrase': 'a donkey', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': True, 'extracted_word': 'donkey'}, {'search_phrase_word': 'chase', 'document_word': 'chase', 'document_phrase': 'chasing', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'chase'}]}])

    def test_multithreading_matching_against_search_phrases(self):
        self._inner_match_against_search_phrases("The hungry lion chased the angry gnu.",
        [{'search_phrase': 'A gnu is chased', 'document': '', 'index_within_document': 3, 'sentences_within_document': 'The hungry lion chased the angry gnu.', 'negated': False, 'uncertain': False, 'involves_coreference': False, 'overall_similarity_measure': '1.0', 'word_matches': [{'search_phrase_word': 'gnu', 'document_word': 'gnu', 'document_phrase': 'the angry gnu', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'gnu'}, {'search_phrase_word': 'chase', 'document_word': 'chase', 'document_phrase': 'chased', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'chase'}]}, {'search_phrase': 'An angry gnu', 'document': '', 'index_within_document': 6, 'sentences_within_document': 'The hungry lion chased the angry gnu.', 'negated': False, 'uncertain': False, 'involves_coreference': False, 'overall_similarity_measure': '1.0', 'word_matches': [{'search_phrase_word': 'angry', 'document_word': 'angry', 'document_phrase': 'angry', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'angry'}, {'search_phrase_word': 'gnu', 'document_word': 'gnu', 'document_phrase': 'the angry gnu', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'gnu'}]}])
        self._inner_match_against_search_phrases("The hungry tiger chased the angry gnu.",
        [{'search_phrase': 'A gnu is chased', 'document': '', 'index_within_document': 3, 'sentences_within_document': 'The hungry tiger chased the angry gnu.', 'negated': False, 'uncertain': False, 'involves_coreference': False, 'overall_similarity_measure': '1.0', 'word_matches': [{'search_phrase_word': 'gnu', 'document_word': 'gnu', 'document_phrase': 'the angry gnu', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'gnu'}, {'search_phrase_word': 'chase', 'document_word': 'chase', 'document_phrase': 'chased', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'chase'}]}, {'search_phrase': 'An angry gnu', 'document': '', 'index_within_document': 6, 'sentences_within_document': 'The hungry tiger chased the angry gnu.', 'negated': False, 'uncertain': False, 'involves_coreference': False, 'overall_similarity_measure': '1.0', 'word_matches': [{'search_phrase_word': 'angry', 'document_word': 'angry', 'document_phrase': 'angry', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'angry'}, {'search_phrase_word': 'gnu', 'document_word': 'gnu', 'document_phrase': 'the angry gnu', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'gnu'}]}, {'search_phrase': 'A tiger chases', 'document': '', 'index_within_document': 3, 'sentences_within_document': 'The hungry tiger chased the angry gnu.', 'negated': False, 'uncertain': False, 'involves_coreference': False, 'overall_similarity_measure': '1.0', 'word_matches': [{'search_phrase_word': 'tiger', 'document_word': 'tiger', 'document_phrase': 'The hungry tiger', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'tiger'}, {'search_phrase_word': 'chase', 'document_word': 'chase', 'document_phrase': 'chased', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'chase'}]}])
        self._inner_match_against_search_phrases(
                "I saw a hungry panther. It was chasing an angry gnu.",
            [{'search_phrase': 'A gnu is chased', 'document': '', 'index_within_document': 8, 'sentences_within_document': 'It was chasing an angry gnu.', 'negated': False, 'uncertain': False, 'involves_coreference': False, 'overall_similarity_measure': '1.0', 'word_matches': [{'search_phrase_word': 'gnu', 'document_word': 'gnu', 'document_phrase': 'an angry gnu', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'gnu'}, {'search_phrase_word': 'chase', 'document_word': 'chase', 'document_phrase': 'chasing', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'chase'}]}, {'search_phrase': 'An angry gnu', 'document': '', 'index_within_document': 11, 'sentences_within_document': 'It was chasing an angry gnu.', 'negated': False, 'uncertain': False, 'involves_coreference': False, 'overall_similarity_measure': '1.0', 'word_matches': [{'search_phrase_word': 'angry', 'document_word': 'angry', 'document_phrase': 'angry', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'angry'}, {'search_phrase_word': 'gnu', 'document_word': 'gnu', 'document_phrase': 'an angry gnu', 'match_type': 'direct', 'similarity_measure': 1.0, 'involves_coreference': False, 'extracted_word': 'gnu'}]}])
